apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-agent
  title: Infrastructure AI Agent
  description: Servicio de IA para generación automática de templates AWS
  tags:
    - ai
    - fastapi
    - python
    - gemini
  annotations:
    github.com/project-slug: giovanemere/demo-infra-ai-agent
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: service
  lifecycle: production
  owner: group:default/developers
  system: infrastructure-ai-platform
  providesApis:
    - ai-agent-api
  dependsOn:
    - resource:default/gemini-api
    - resource:default/postgresql-db
