apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql-db
  title: PostgreSQL Database
  description: PostgreSQL database for Backstage
spec:
  type: database
  owner: group:default/developers
  system: infrastructure-ai-platform
